version: "2.3"

services:
  tfg-use-case-core-srv:
    container_name: "tfg-use-case-core"
    network_mode: host
    image: tfg_image
    volumes:
      - ~/dockers/.xauth_docker/share:/tmp/xauth
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ~/workspaces/tfg_ws/src/tfg/:/ros_ws/src/tfg/ 
      #- /tmp/.xauth_docker/share:/tmp/xauth
    tty: true
    stdin_open: true
    environment:
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=/tmp/xauth/.docker.xauth
    devices:
      - /dev/dri:/dev/dri 
      - /dev/video0:/dev/video0
      - /dev/video1:/dev/video1
      - /dev/snd:/dev/snd
